---
version: "2"
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.yml
  stylelint:
    enabled: true
exclude_patterns:
  - "node_modules/*"
  - "**/*.test.js"
  - "**/*.test.jsx"
  - "src/registerServiceWorker.js"
  - "src/index.js"
  - "src/setupTests.js"
  - "src/store.js"