---
engines:
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      extensions:
        - .js
        - .jsx
    checks:
      import/no-duplicates:
        enabled: true
      no-template-curly-in-string:
        enabled: false
      import/no-unresolved:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
      import/no-named-as-default-member:
        enabled: false
  stylelint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.scss"
  - "!**.test.js"
exclude_paths:
  - node_modules/**/*